// Generated by Wrangler by running `wrangler types`

interface Env {
  OAUTH_KV: KVNamespace
  MONDAY_CLIENT_ID: string
  MONDAY_CLIENT_SECRET: string
  MCP_OBJECT: DurableObjectNamespace<import('./src/index').MyMCP>
  AI: Ai
}
