export enum AppFeatureType {
  AppFeatureStatusColumn = 'AppFeatureStatusColumn',
  AppFeatureAccountSettingsView = 'AppFeatureAccountSettingsView',
  AppFeatureBoardColumnExtension = 'AppFeatureBoardColumnExtension',
  AppFeatureGroupMenuAction = 'AppFeatureGroupMenuAction',
  AppFeatureProductView = 'AppFeatureProductView',
  AppFeatureAdminView = 'AppFeatureAdminView',
  AppFeatureDropdownColumn = 'AppFeatureDropdownColumn',
  AppFeatureWorkspaceView = 'AppFeatureWorkspaceView',
  AppFeatureDocActions = 'AppFeatureDocActions',
  AppFeatureItemMenuAction = 'AppFeatureItemMenuAction',
  AppFeatureItemBatchAction = 'AppFeatureItemBatchAction',
  AppFeatureItemView = 'AppFeatureItemView',
  AppFeatureBoardView = 'AppFeatureBoardView',
  AppFeatureDashboardWidget = 'AppFeatureDashboardWidget',
  AppFeatureObject = 'AppFeatureObject',
  AppFeatureAiBoardMainMenuHeader = 'AppFeatureAiBoardMainMenuHeader',
  AppFeatureAiItemUpdateActions = 'AppFeatureAiItemUpdateActions',
  AppFeatureAiDocSlashCommand = 'AppFeatureAiDocSlashCommand',
  AppFeatureAiDocContextualMenu = 'AppFeatureAiDocContextualMenu',
  AppFeatureAiDocQuickStart = 'AppFeatureAiDocQuickStart',
  AppFeatureAiDocTopBar = 'AppFeatureAiDocTopBar',
  AppFeatureBlock = 'AppFeatureBlock',
  AppFeatureFieldType = 'AppFeatureFieldType',
  AppFeatureCredentials = 'AppFeatureCredentials',
}

export enum MondayAppsToolCategory {
  APP = 'app',
  APP_VERSION = 'app_version',
  APP_FEATURE = 'app_feature',
  STORAGE = 'storage',
  MONDAY_CODE = 'monday_code',
}
